### ISSUE TITLE
Error getting collection_stats with incorrect name

### ISSUE THREAD

**Issue by m4xx1m** [zseta/python-opensea#10]
I'm trying to find collection stats for not existing collection and i recive
> api = OpenseaAPI()
> api.collection_stats(collection_slug="asd")

```
Traceback (most recent call last):
  File "/home/m4xx1m/jp3g3r/venv/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/m4xx1m/jp3g3r/venv/lib/python3.10/site-packages/opensea/opensea_api.py", line 236, in collection_stats
    return self._make_request(endpoint, export_file_name=export_file_name)
  File "/home/m4xx1m/jp3g3r/venv/lib/python3.10/site-packages/opensea/opensea_api.py", line 67, in _make_request
    return response.json()
  File "/home/m4xx1m/jp3g3r/venv/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0 
```
![image](https://user-images.githubusercontent.com/59927482/152262289-5bd680ce-73c4-4a1f-b246-4b9b8a826c13.png)

**Comment by zseta** [comment]
Hi! @m4xx1m ,
What you are saying is that there should be some meaningful error message saying that's a non-existing collection or Not found or something similar?

**Comment by m4xx1m** [comment]
Hi! Sorry for the long answer... I think it's a problem with opensea
![2022-02-06_18-58](https://user-images.githubusercontent.com/59927482/152689419-f8191709-8792-4dfb-b4c2-4ec7bd7ceeab.png)

**Comment by zseta** [comment]
I'm closing this now, but if you have other issues in the future feel free to open a new one
